package bio

import (
	"bufio"
	"bytes"
	"encoding/hex"
	"os"
	"strconv"
	"strings"
	"testing"
)

type bioCase struct {
	ns  []uint32
	vs  []uint32
	enc []byte
}

func loadBioVectors(t *testing.T) []bioCase {
	t.Helper()
	f, err := os.Open("../../testdata/vectors/bio/bio.txt")
	if err != nil {
		t.Fatalf("open vectors: %v", err)
	}
	defer f.Close()

	var cases []bioCase
	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 1<<20), 1<<20)
	var cur bioCase
	for sc.Scan() {
		fld := strings.Fields(sc.Text())
		if len(fld) == 0 {
			continue
		}
		switch fld[0] {
		case "SEQ":
			cur = bioCase{}
			for _, tok := range fld[1:] {
				parts := strings.SplitN(tok, ":", 2)
				n, _ := strconv.ParseUint(parts[0], 10, 32)
				v, _ := strconv.ParseUint(parts[1], 10, 32)
				cur.ns = append(cur.ns, uint32(n))
				cur.vs = append(cur.vs, uint32(v))
			}
		case "ENC":
			h := ""
			if len(fld) > 1 {
				h = fld[1]
			}
			b, err := hex.DecodeString(h)
			if err != nil {
				t.Fatalf("hex %q: %v", h, err)
			}
			cur.enc = b
			cases = append(cases, cur)
		}
	}
	if err := sc.Err(); err != nil {
		t.Fatalf("scan: %v", err)
	}
	return cases
}

// TestEncodeVectors checks that encoding each (n,v) sequence and flushing
// reproduces the C-generated bytes.
func TestEncodeVectors(t *testing.T) {
	cases := loadBioVectors(t)
	if len(cases) == 0 {
		t.Fatal("no vectors")
	}
	for ci, c := range cases {
		buf := make([]byte, len(c.ns)*8+16)
		b := NewEncoder(buf)
		for i := range c.ns {
			b.Write(c.vs[i], c.ns[i])
		}
		if !b.Flush() {
			t.Fatalf("case %d: flush failed", ci)
		}
		got := buf[:b.NumBytes()]
		if !bytes.Equal(got, c.enc) {
			t.Errorf("case %d: encode got %x want %x", ci, got, c.enc)
		}
	}
}

// TestDecodeVectors checks that decoding the C-generated bytes with the same
// n-sequence recovers the original values.
func TestDecodeVectors(t *testing.T) {
	cases := loadBioVectors(t)
	for ci, c := range cases {
		b := NewDecoder(c.enc)
		for i := range c.ns {
			got := b.Read(c.ns[i])
			if got != c.vs[i] {
				t.Errorf("case %d sym %d: decode got %d want %d", ci, i, got, c.vs[i])
			}
		}
	}
}

// TestRoundTrip covers a few hand-written edge cases including inalign.
func TestRoundTrip(t *testing.T) {
	syms := []struct{ v, n uint32 }{
		{0xFF, 8}, {1, 1}, {0, 1}, {0xFFFF, 16}, {0x7F, 7}, {0xFFFFFFFF, 32},
	}
	buf := make([]byte, 256)
	enc := NewEncoder(buf)
	for _, s := range syms {
		enc.Write(s.v, s.n)
	}
	if !enc.Flush() {
		t.Fatal("flush failed")
	}
	dec := NewDecoder(buf[:enc.NumBytes()])
	for _, s := range syms {
		if got := dec.Read(s.n); got != s.v {
			t.Errorf("roundtrip %v: got %#x", s, got)
		}
	}
}

// TestNumBytesEmpty checks that flushing an empty encoder emits the trailing
// byte(s) exactly as C does.
func TestNumBytesEmpty(t *testing.T) {
	buf := make([]byte, 16)
	b := NewEncoder(buf)
	if !b.Flush() {
		t.Fatal("flush failed")
	}
	// After init ct=8, buf=0; byteout emits one 0x00 (buf!=0xff00) so ct=8, one
	// byte written, then ct!=7 so no second byte.
	if b.NumBytes() != 1 {
		t.Errorf("empty flush NumBytes = %d, want 1", b.NumBytes())
	}
}

// TestFullBufferEncode checks that a too-small output buffer stops writing (the
// byteout false path) without panicking, matching the C bounds guard.
func TestFullBufferEncode(t *testing.T) {
	buf := make([]byte, 1)
	b := NewEncoder(buf)
	for i := 0; i < 100; i++ {
		b.Write(0xFFFFFFFF, 32)
	}
	b.Flush()
	if b.NumBytes() > len(buf) {
		t.Errorf("wrote past buffer: NumBytes=%d", b.NumBytes())
	}
}

// FuzzDecode exercises the decoder against arbitrary bytes and read sizes,
// ensuring it never panics on untrusted input (bounds and stuffing safety).
func FuzzDecode(f *testing.F) {
	f.Add([]byte{0x00}, uint32(1))
	f.Add([]byte{0xFF, 0xFF, 0xFF}, uint32(32))
	f.Add([]byte{}, uint32(5))
	f.Fuzz(func(t *testing.T, data []byte, n uint32) {
		// Constrain n to the asserted C domain (1..32).
		n = n%32 + 1
		b := NewDecoder(data)
		// Read repeatedly; must not panic regardless of buffer exhaustion.
		for i := 0; i < 64; i++ {
			_ = b.Read(n)
		}
		_ = b.InAlign()
		_ = b.NumBytes()
	})
}
