package cio

import (
	"bufio"
	"bytes"
	"encoding/hex"
	"errors"
	"io"
	"math"
	"os"
	"strconv"
	"strings"
	"testing"
)

func mustHex(t *testing.T, s string) []byte {
	t.Helper()
	b, err := hex.DecodeString(s)
	if err != nil {
		t.Fatalf("hex %q: %v", s, err)
	}
	return b
}

// TestByteOrderVectors replays the C-generated byte-order helper vectors.
func TestByteOrderVectors(t *testing.T) {
	f, err := os.Open("../../testdata/vectors/cio/bytes.txt")
	if err != nil {
		t.Fatalf("open vectors: %v", err)
	}
	defer f.Close()

	sc := bufio.NewScanner(f)
	line := 0
	for sc.Scan() {
		line++
		fld := strings.Fields(sc.Text())
		if len(fld) == 0 {
			continue
		}
		switch fld[0] {
		case "wb_be", "wb_le":
			val, _ := strconv.ParseUint(fld[1], 10, 32)
			nb, _ := strconv.ParseUint(fld[2], 10, 32)
			want := mustHex(t, fld[3])
			buf := make([]byte, 8)
			if fld[0] == "wb_be" {
				WriteBytesBE(buf, uint32(val), uint32(nb))
			} else {
				WriteBytesLE(buf, uint32(val), uint32(nb))
			}
			if !bytes.Equal(buf[:nb], want) {
				t.Errorf("line %d %s val=%d nb=%d: got %x want %x", line, fld[0], val, nb, buf[:nb], want)
			}
		case "rb_be", "rb_le":
			in := mustHex(t, fld[1])
			nb, _ := strconv.ParseUint(fld[2], 10, 32)
			want, _ := strconv.ParseUint(fld[3], 10, 32)
			var got uint32
			if fld[0] == "rb_be" {
				got = ReadBytesBE(in, uint32(nb))
			} else {
				got = ReadBytesLE(in, uint32(nb))
			}
			if got != uint32(want) {
				t.Errorf("line %d %s in=%x nb=%d: got %d want %d", line, fld[0], in, nb, got, want)
			}
		case "wd_be", "wd_le":
			bits, _ := strconv.ParseUint(fld[1], 16, 64)
			want := mustHex(t, fld[2])
			buf := make([]byte, 8)
			d := math.Float64frombits(bits)
			if fld[0] == "wd_be" {
				WriteDoubleBE(buf, d)
			} else {
				WriteDoubleLE(buf, d)
			}
			if !bytes.Equal(buf, want) {
				t.Errorf("line %d %s bits=%016x: got %x want %x", line, fld[0], bits, buf, want)
			}
		case "rd_be", "rd_le":
			in := mustHex(t, fld[1])
			wantBits, _ := strconv.ParseUint(fld[2], 16, 64)
			var d float64
			if fld[0] == "rd_be" {
				d = ReadDoubleBE(in)
			} else {
				d = ReadDoubleLE(in)
			}
			if got := math.Float64bits(d); got != wantBits {
				t.Errorf("line %d %s in=%x: got %016x want %016x", line, fld[0], in, got, wantBits)
			}
		case "wf_be", "wf_le":
			bits, _ := strconv.ParseUint(fld[1], 16, 32)
			want := mustHex(t, fld[2])
			buf := make([]byte, 4)
			f32 := math.Float32frombits(uint32(bits))
			if fld[0] == "wf_be" {
				WriteFloatBE(buf, f32)
			} else {
				WriteFloatLE(buf, f32)
			}
			if !bytes.Equal(buf, want) {
				t.Errorf("line %d %s bits=%08x: got %x want %x", line, fld[0], bits, buf, want)
			}
		case "rf_be", "rf_le":
			in := mustHex(t, fld[1])
			wantBits, _ := strconv.ParseUint(fld[2], 16, 32)
			var f32 float32
			if fld[0] == "rf_be" {
				f32 = ReadFloatBE(in)
			} else {
				f32 = ReadFloatLE(in)
			}
			if got := math.Float32bits(f32); got != uint32(wantBits) {
				t.Errorf("line %d %s in=%x: got %08x want %08x", line, fld[0], in, got, wantBits)
			}
		default:
			t.Fatalf("line %d: unknown tag %q", line, fld[0])
		}
	}
	if line == 0 {
		t.Fatal("no vectors read")
	}
}

// TestLittleEndianBytes covers the clean little-endian-of-low-nbBytes
// semantics for partial widths, which the C _BE host-specialisation does not
// realise cleanly (so it is not in the oracle file). WriteBytesLE writes the
// nbBytes least-significant bytes, least significant first.
func TestLittleEndianBytes(t *testing.T) {
	cases := []struct {
		val  uint32
		nb   uint32
		want []byte
	}{
		{0x12345678, 1, []byte{0x78}},
		{0x12345678, 2, []byte{0x78, 0x56}},
		{0x12345678, 3, []byte{0x78, 0x56, 0x34}},
		{0x12345678, 4, []byte{0x78, 0x56, 0x34, 0x12}},
		{0x0000ABCD, 2, []byte{0xCD, 0xAB}},
	}
	for _, c := range cases {
		buf := make([]byte, 4)
		WriteBytesLE(buf, c.val, c.nb)
		if !bytes.Equal(buf[:c.nb], c.want) {
			t.Errorf("WriteBytesLE(%#x,%d) = %x, want %x", c.val, c.nb, buf[:c.nb], c.want)
		}
		if got := ReadBytesLE(c.want, c.nb); got != c.val&mask(c.nb) {
			t.Errorf("ReadBytesLE(%x,%d) = %#x, want %#x", c.want, c.nb, got, c.val&mask(c.nb))
		}
	}
}

func mask(nb uint32) uint32 {
	if nb >= 4 {
		return 0xFFFFFFFF
	}
	return (1 << (8 * nb)) - 1
}

// TestMemoryInputRead exercises the buffered read path including the partial
// read at end-of-stream and the subsequent ErrEnd.
func TestMemoryInputRead(t *testing.T) {
	data := []byte{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}
	s := NewMemoryInputStream(data)

	buf := make([]byte, 4)
	// Two full reads.
	for i := 0; i < 2; i++ {
		n, err := s.Read(buf, nil)
		if n != 4 || err != nil {
			t.Fatalf("read %d: got n=%d err=%v", i, n, err)
		}
		if !bytes.Equal(buf, data[i*4:i*4+4]) {
			t.Fatalf("read %d mismatch: %v", i, buf)
		}
	}
	if s.Tell() != 8 {
		t.Fatalf("tell = %d, want 8", s.Tell())
	}
	// Partial read of the last 2 bytes.
	n, err := s.Read(buf, nil)
	if n != 2 || err != nil {
		t.Fatalf("partial read: got n=%d err=%v", n, err)
	}
	if !bytes.Equal(buf[:2], data[8:]) {
		t.Fatalf("partial mismatch: %v", buf[:2])
	}
	// Now at end: ErrEnd.
	n, err = s.Read(buf, nil)
	if n != 0 || !errors.Is(err, ErrEnd) {
		t.Fatalf("eof read: got n=%d err=%v", n, err)
	}
}

// TestMemoryInputSkipSeek covers skip, skip-past-end and seek/tell.
func TestMemoryInputSkipSeek(t *testing.T) {
	data := make([]byte, 20)
	for i := range data {
		data[i] = byte(i)
	}
	s := NewMemoryInputStream(data)

	n, err := s.Skip(5, nil)
	if n != 5 || err != nil {
		t.Fatalf("skip 5: n=%d err=%v", n, err)
	}
	if s.Tell() != 5 {
		t.Fatalf("tell after skip = %d", s.Tell())
	}
	buf := make([]byte, 3)
	if _, err := s.Read(buf, nil); err != nil {
		t.Fatalf("read after skip: %v", err)
	}
	if !bytes.Equal(buf, data[5:8]) {
		t.Fatalf("read after skip mismatch: %v", buf)
	}

	// Seek back to an absolute position.
	if err := s.SeekTo(2, nil); err != nil {
		t.Fatalf("seek: %v", err)
	}
	if s.Tell() != 2 {
		t.Fatalf("tell after seek = %d", s.Tell())
	}
	if _, err := s.Read(buf, nil); err != nil {
		t.Fatalf("read after seek: %v", err)
	}
	if !bytes.Equal(buf, data[2:5]) {
		t.Fatalf("read after seek mismatch: %v", buf)
	}

	// Skip past end: clamps to the data length and reports the clamped count.
	s2 := NewMemoryInputStream(data)
	n, err = s2.Skip(100, nil)
	if err != nil {
		t.Fatalf("skip past end: err=%v", err)
	}
	if n != 20 {
		t.Fatalf("skip past end: got %d want 20", n)
	}
	if s2.NumberByteLeft() != 0 {
		t.Fatalf("bytes left = %d, want 0", s2.NumberByteLeft())
	}
	if _, err := s2.Read(buf, nil); !errors.Is(err, ErrEnd) {
		t.Fatalf("read after skip-past-end: err=%v", err)
	}
}

// TestMemoryOutput writes across the internal buffer and reads the result back.
func TestMemoryOutput(t *testing.T) {
	s := NewMemoryOutputStream()
	want := make([]byte, 3000)
	for i := range want {
		want[i] = byte(i * 7)
	}
	off := 0
	for off < len(want) {
		end := off + 512
		if end > len(want) {
			end = len(want)
		}
		n, err := s.Write(want[off:end], nil)
		if err != nil {
			t.Fatalf("write: %v", err)
		}
		off += n
	}
	if s.Tell() != int64(len(want)) {
		t.Fatalf("tell = %d, want %d", s.Tell(), len(want))
	}
	if err := s.Flush(nil); err != nil {
		t.Fatalf("flush: %v", err)
	}
	if !bytes.Equal(s.Bytes(), want) {
		t.Fatalf("output mismatch")
	}
}

// TestReadSeekerInput checks the io.ReadSeeker constructor and length probe.
func TestReadSeekerInput(t *testing.T) {
	data := []byte("hello, jpeg2000 world")
	s, err := NewReadSeekerInputStream(bytes.NewReader(data))
	if err != nil {
		t.Fatalf("new: %v", err)
	}
	if uint64(s.NumberByteLeft()) != uint64(len(data)) {
		t.Fatalf("length = %d, want %d", s.NumberByteLeft(), len(data))
	}
	if !s.HasSeek() {
		t.Fatal("HasSeek = false")
	}
	buf := make([]byte, len(data))
	total := 0
	for total < len(data) {
		n, err := s.Read(buf[total:], nil)
		if err != nil && !errors.Is(err, io.EOF) {
			t.Fatalf("read: %v", err)
		}
		if n == 0 {
			break
		}
		total += n
	}
	if !bytes.Equal(buf, data) {
		t.Fatalf("readseeker mismatch: %q", buf)
	}
}
